// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzxAjiBe1dBlXnUBX92jAcbwhBlBQGnBI',
    appId: '1:860338486644:web:46c0282c21fc1b17c04021',
    messagingSenderId: '860338486644',
    projectId: 'easylogin-94d54',
    authDomain: 'easylogin-94d54.firebaseapp.com',
    storageBucket: 'easylogin-94d54.firebasestorage.app',
    measurementId: 'G-1VMSTS8G4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuXIAbNLvsAxYMcsNWgn1q1MJHS9DhZpo',
    appId: '1:860338486644:android:f1985efe8e6ccdc7c04021',
    messagingSenderId: '860338486644',
    projectId: 'easylogin-94d54',
    storageBucket: 'easylogin-94d54.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzxAjiBe1dBlXnUBX92jAcbwhBlBQGnBI',
    appId: '1:860338486644:web:b33e061e96123773c04021',
    messagingSenderId: '860338486644',
    projectId: 'easylogin-94d54',
    authDomain: 'easylogin-94d54.firebaseapp.com',
    storageBucket: 'easylogin-94d54.firebasestorage.app',
    measurementId: 'G-V3R41X7CWZ',
  );
}
